### ISSUE TITLE
devkitA64 FindDevice doesn't handle relative paths with colons correctly

### ISSUE THREAD

**Issue by crc-32** [devkitPro/newlib#14]
mkdir used as an example as it's where the bug was first noticed.

https://github.com/devkitPro/newlib/blob/devkitA64/libgloss/libsysbase/iosupport.c#L70
https://github.com/devkitPro/newlib/blob/devkitA64/libgloss/libsysbase/iosupport.c#L80
When provided with the path, these lines then assume that the first colon it finds is separating the device from the path, which isn't necessarily true as relative paths don't include any devices, so the function ends up trying to resolve the first half before the colon as a device resulting in it returning -1 making mkdir read at index -1 of devoptab_list causing a segfault, this likely affects other fs functions.

**Comment by fincs** [comment]
The colon `:` isn't a valid filename character. How can this even happen normally?

**Comment by crc-32** [comment]
Surely it's better to handle reserved characters and report back with some form of error instead of causing a segfault. It can happen when user input is provided verbatim to, for example, the mkdir function or possibly in FTP scenarios where a path is created from a Linux client that includes a colon (as Linux supports colons in filenames)

**Comment by fincs** [comment]
The underlying filesystem used on the Switch does not support colons in filenames either because it's FAT32/exFAT. If you're really concerned about this (which shouldn't be an issue during normal usage), I think you should perform filename sanitization on your own. I can't think of a reason why you would want to have a colon in a filename anyway. It would also help if you explained with more detail what are you trying to accomplish, and why does it need colons in filenames, instead of being vague.

**Comment by WinterMute** [comment]
fixed with https://github.com/devkitPro/newlib/commit/e83eca4aa47e5b0c7dadf8903fe104f9f9cd8257
